FROM golang:1.21 AS golangapp

WORKDIR /usr/src/app

COPY go/src .
# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
RUN go mod download && go mod verify

RUN go build ./main.go

EXPOSE 50051

CMD ./main